apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: go-app-tls
  namespace: istio-system
spec:
  secretName: go-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - app.your-domain.example
