{{- if .Values.istio.enabled }}
{{- $fullName := include "go-sample-app.fullname" . -}}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ $fullName }}-gateway
spec:
  selector:
    istio: {{ .Values.istio.ingressGatewaySelector }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.istio.host | quote }}
    {{- if .Values.istio.tls.enabled }}
    tls:
      httpsRedirect: true
    {{- end }}
  {{- if .Values.istio.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - {{ .Values.istio.host | quote }}
    tls:
      mode: {{ .Values.istio.tls.mode }}
      credentialName: {{ .Values.istio.tls.credentialName | quote }}
  {{- end }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ $fullName }}-frontend
spec:
  hosts:
  - {{ .Values.istio.host | quote }}
  gateways:
  - {{ $fullName }}-gateway
  http:
  - route:
    - destination:
        host: {{ $fullName }}-frontend.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.frontend.servicePort }}
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ $fullName }}-backend-istio-mtls
spec:
  host: {{ $fullName }}-backend.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- if .Values.istio.mtlsStrict }}
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
{{- end }}
{{- end }}
